<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  SAPIEN Technologies, Inc., PowerShell Studio 2020 v5.7.172
     Generated on:       4/6/2020 16:37
     Generated by:       Claussen
     Organization:       NEOnet
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by PowerShell Studio 2020
#>


SetupFortigateConfigVariable
SetupFortigateURICommonParametersToIgnore

Export-ModuleMember "*-*"
Export-ModuleMember 'GetFortigateConfigVariable'
